workflows:
  ios-workflow:
    name: iOS Workflow (sin firma)
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Build iOS app (sin codesign)
        script: |
          flutter build ios --release --no-codesign
      - name: Empaquetar IPA sin firmar
        script: |
          mkdir -p build/ios/iphoneos/Payload
          cp -r build/ios/iphoneos/Runner.app build/ios/iphoneos/Payload/
          cd build/ios/iphoneos
          zip -r ramotracker-unsigned.ipa Payload
    artifacts:
      - build/ios/iphoneos/*.ipa
