workflows:
  ios-workflow:
    name: iOS Workflow (sin firma)
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Build iOS app (sin codesign)
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/*.app
